apiVersion: v1
kind: Pod
metadata:
  name: flask
spec:
  containers:
  - name: flask
    image: docker.io/library/flask:latest
    ports:
    - containerPort: 5000
    imagePullPolicy: Never
  - name: nginx
    image: docker.io/library/nginx:latest
    ports:
    - containerPort: 80
    imagePullPolicy: Never
