apiVersion: v1
kind: Pod
metadata:
  name: flask-1
  labels:
    app: flask1
spec:
  containers:
  - name: flask
    image: docker.io/library/flask:latest
    ports:
    - containerPort: 5000
    imagePullPolicy: Never
    env:
    - name: POD
      value: POD-1
---
apiVersion: v1
kind: Pod
metadata:
  name: flask-2
  labels:
    app: flask2
spec:
  containers:
  - name: flask
    image: docker.io/library/flask:latest
    ports:
    - containerPort: 5000
    imagePullPolicy: Never
    env:
    - name: POD
      value: POD-2
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service1
spec:
  selector:
    app: flask1
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service2
spec:
  selector:
    app: flask2
  ports:
  - port: 80
    targetPort: 5000
